config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { registrations: 'user/registrations' }

  root to: 'packages#new'
  resources :packages
  resources :users, only: :show

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="/">Workhorse delivery</a>
      <ul class="navbar-nav me-auto">
      <li class="nav-item">
        <a href=<%= packages_path %> class="btn btn-info" role="button">My packages</a>
      </li>
      <% if user_signed_in? %>
        Logged in as <strong> <%= current_user.email %> </strong>.
        <li class="nav-item">
          <a href=<%= edit_user_registration_path %> class="btn btn-info" role="button">Edit profile</a>
        </li>
        <li class="nav-item">
          <a href=<%= destroy_user_session_path %> class="btn btn-info" role="button">Logout</a>
        </li>
        <li class="nav-item">
          <a href=<%= user_path(current_user.id) %> class="btn btn-info" role="button">User info</a>
        </li>
      <% else %>
        <li class="nav-item">
          <a href=<%= new_user_registration_path %> class="btn btn-info" role="button">SignUp</a>
        </li>
        <li class="nav-item">
          <a href=<%= new_user_session_path %> class="btn btn-info" role="button">Login</a>
        </li>
      <% end %>
      </ul>
    </div>
  </nav>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>